### ISSUE TITLE
One question about Line 247 in custom_main_binary_imagenet.py

### ISSUE THREAD

**Issue by haichaoyu** [ruizhoud/DistributionLoss#4]
Hi Ruizhou, 

This paper on weight regularization is quite interesting!

I have a question about the code [here](https://github.com/ruizhoud/DistributionLoss/blob/9b6eafc5d761f59a96f83e6c6d83905083037f95/custom_main_binary_imagenet.py#L247). After this line executed, all the weights are forced to be in [-1, 1]. If so, how could gradient mismatch be mitigated/solved?

Haichao

**Comment by ruizhoud** [comment]
Hi Haichao,

BNN quantize (1) weights and (2) activations to +1 or -1. This paper mainly tackles the three problems induced by activation quantization. This line of code is about weight quantization, and it just follows the previous [work](https://github.com/itayhubara/BinaryNet.pytorch). 

P.S. My feeling is that although the HardTanh approximation for weight quantization also has the mismatch problem, it is not a very severe problem compared to activation quantization, mainly because the mismatch for weight quantization does not accumulate across layers. But definitely it is an interesting problem to check. 

Thanks,
Ruizhou

**Comment by haichaoyu** [comment]
@ruizhoud Got it. Thanks.
